name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        env:
          # FIXME: once #14@ghjk lands
          GHJK_VERSION: 6040bb3

      - name: Check avail of pnpm
        shell: bash
        run: pnpm --version
